"""Initial migration

Revision ID: 14438f3c3a0d
Revises: 
Create Date: 2024-12-22 12:12:35.807134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14438f3c3a0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('pet_name', sa.String(), nullable=False),
    sa.Column('pet_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pet_sitters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sitter_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('pet_owner_id', sa.Integer(), nullable=False),
    sa.Column('pet_sitter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pet_owner_id'], ['pet_owners.id'], name=op.f('fk_appointments_pet_owner_id_pet_owners')),
    sa.ForeignKeyConstraint(['pet_sitter_id'], ['pet_sitters.id'], name=op.f('fk_appointments_pet_sitter_id_pet_sitters')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_table('pet_sitters')
    op.drop_table('pet_owners')
    # ### end Alembic commands ###
